application: sidm
version: 1
runtime: python
api_version: 1

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?.*\.templ$
- ^(.*/)?thumbs.db

handlers:
- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  
- url: /timesheets/
  static_dir: timesheets
  mime_type: text/html

- url: (.*)/
  static_files: static/index.html
  upload: static/index.html

- url: /
  static_dir: static
  

