baseURL = "http://www.sidmitra.com/"
buildDrafts = false
canonifyURLs = false
disqusShortName = "sidmitra"
languageCode = "en-US"
pluralizeListTitles = false
pygmentsUseClasses = true
theme="custom"
title = "Homepage"
verbose = true
verboseLog = true
watch = true

[permalinks]
fixed = ":title/"
blog = "blog/:slug/"

[taxonomies]
tag = "tags"
category = "categories"

[params]
author = "Siddharth Mitra"
DateForm = "Jan 2, 2006"
DateFormFull = "January 2, 2006"
Description = "Personal homepage of Siddharth Mitra"

cachebuster = true
highlightjs = true
lang = "en"

avatar = "frog3d.jpg" # path to image in static dir e.g img/avatar.png
faviconfile = "img/favicon.ico"
extracssfiles = [ "" ] # In your `static/css`, add/remove files as necessary.

# social
email = "blog@sidmitra.com"
github = "//github.com/sidmitra"
linkedin = "//linkedin.com/in/sidmitra"
twitter = "//twitter.com/sidmitra"

# gatracker = "XYZ"