baseurl = "https://www.sidmitra.com/"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Siddharth Mitra"
title = "Siddharth Mitra"
pygmentsuseclasses = true
#disqusshortname = "" # Comment out to disable Disqus.
pluralizelisttitles = false

[permalinks]
fixed = ":title/"
blog = "blog/:slug/"

[params]
author = "Siddharth Mitra"
# gravatar = "" # do not use in the same time as Avatar
# avatar = "" # path to image in static dir e.g img/avatar.png (do not use in the same time as Gravatar)
cachebuster = true
dateform = "Nov 24, 2016"
dateformfull = "Mon Nov 2 2016 20:04:05 CLT"
description = "Personal homepage of Siddharth Mitra"
highlightjs = true
initials = "sm" # Displayed on single post page; DEPRECATED in v0.3.0.
lang = "en"
faviconfile = "img/favicon.ico"
extracssfiles = [ "/css/override.css" ] # In your `static/css`, add/remove files as necessary.

# social
email = "sidmitra.del@gmail.com"
github = "//github.com/sidmitra"
linkedin = "//linkedin.com/in/sidmitra"
twitter = "//twitter.com/sidmitra"

# gatracker = "XYZ"