name = "custom"
license = "MIT"
licenselink = ""
description = ""
homepage = ""
tags = ["open-sans", "minimal", "clean", "ionicons", "comments"]
features = ["blog", "responsive", "404", "icons", "disqus", "metadata"]
min_version = 0.15

[author]
  name = ""
  homepage = ""
