runtime: python27
api_version: 1
threadsafe: true

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$

handlers:
# Handle homepage
- url: /$
  static_files: index.html
  upload: index.html

- url: /blog/(.+)/$
  static_files: blog/\1/index.html
  upload: blog/(.+)/index.html

# Redirect Subdir to index.html
- url: /(.+)/
  static_files: \1/index.html
  upload: (.+)/index.html

# Handle all other files
- url: /(.+)
  static_files: \1
  upload: (.+)
